CI Deployment1

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -6,6 +6,37 @@ on:
       - main
 
 jobs:
+    # 🔍 JOB 1: Code Quality + Security Checks
+  checks:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Setup Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.12'
+
+      - name: Install Dependencies
+        run: |
+          pip install -r requirements.txt
+          pip install flake8 pylint bandit pip-audit
+
+      - name: Run Flake8
+        run: flake8 .
+
+      - name: Run Pylint
+        run: pylint online_voting_system || true
+        # ⚠️ don't fail pipeline yet (optional)
+
+      - name: Run Bandit (Security Scan)
+        run: bandit -r . -ll
+
+      - name: Run pip-audit (Dependency Scan)
+        run: pip-audit
+        
   deploy:
     runs-on: ubuntu-latest
 
